spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/JohnVithor/SpringConfigFiles"
          search-paths: "{application}/{profile}"
          default-label: "main"
server:
  port: 8888